
# SEO settings
title: "Nói "
title2: " Chuyện" # default: ""
description: "."
keywords: ""
url: http://trinq.github.io# site url
#baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: ""
twitter_username: ""
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "NQ Tri "
  job      :  "freelaner"
  bio      : ""
  thumb    : /images/author.jpg
  email    : triquang13@gmail.com
  url      : http://trinq.github.io
  github   : http://github.com/trinq
  twitter  : http://twitter.com/kihote
  facebook : 
  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@kihote"
# Outputting
timezone: UTC+7

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
