# SEO settings
title: "Trinq Zone;"
description: ""
keywords: ""
url: "https://trinq.github.io" # Site url (default: "")
#baseurl: "" # Apply repo name if use it under gh-pages branch
baseurl: null # Apply null if repo name is something like username.github.io

# Site analytics
google_analytics: 

# Disqus
disqus_shortname: hnbloggithub
# Site author info
author:
  name: "Quang Tri"
  email: triquang13@gmail.com
  nickname: "TriNQ"
  display_bio: true # Edit file in /_includes/bio.html
  website: http://trinq.github.io

# Social settings
og_locale: "en_US"
display_social_icons: true # Edit file in /_includes/social_links.html
github:
  username: trinq
facebook:
  profile_url: 
twitter:
  username: kihote

# Build settings
#source: ./
#destination: ../heiswayi.github.io/
source: ./
destination: ./_site

permalink: /:year/:title
markdown: kramdown
highlighter: rouge

timezone: Asia/Kuala_Lumpur

exclude: ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  sass_dir: assets/scss
  style: compressed # expanded

gems:
  - jekyll-sitemap
